spring:
  application:
    name: user-service

  config:
    import: configserver:http://localhost:8888  # This line is required in Spring Boot 3.1+

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
